// Shared Playlist placeholder while the S4-backed library is the active source.
const songs = [
  {
    name: "Happy",
    artist: "Pharrell Williams",
    objectKey: "jMusic/Happy.mp3",
    play: true,
  },
  {
    name: "Run Run Run",
    artist: "Sia",
    objectKey: "jMusic/Sia Run Run Run.mp3",
    play: true,
  },
  {
    name: "Skeletons",
    artist: "Sia",
    objectKey: "jMusic/Sia Skeletons.mp3",
    play: true,
  },
  {
    name: "Always Gonna Fight",
    artist: "Sia & Billie Eilish",
    objectKey: "jMusic/Sia & Billie Eilish Always Gonna Fight.mp3",
    play: true,
  },
  {
    name: "Live Or Die",
    artist: "Sia",
    objectKey: "jMusic/Sia Live Or Die.mp3",
    play: true,
  },
  {
    name: "Born to Run",
    artist: "Sia",
    objectKey: "jMusic/Sia Born To Run (New 26 Unreleased).mp3",
    play: true,
  },
  {
    name: "Fearless in the Fade",
    artist: "Sia",
    objectKey: "jMusic/Sia Fearless in the Fade.mp3",
    play: true,
  },
  {
    name: "I Choose Me",
    artist: "Sia",
    objectKey: "jMusic/Sia - I Choose Me.mp3",
    play: true,
    },
    {
      name: "Play Me",
      artist: "Neil Diamond",
      objectKey: "jMusic/Play Me.mp3",
      play: true,
    },  
    {
      name: "Beloved Wife",
      artist: "Natalie Merchant",
      objectKey: "jMusic/Natalie Merchant - Beloved Wife.mp3",
      play: true,
    },
  {
    name: "Stay Out Of AA",
    artist: "Walker Hayes",
    objectKey: "jMusic/AA.mp3",
    play: true,
  },
  {
    name: "Beloved",
    artist: "Mumford & Sons",
    objectKey: "jMusic/Beloved.mp3",
    play: true,
  },
  {
    name: "Home",
    artist: "Edward Sharpe & The Magnetic Zeros",
    objectKey: "jMusic/Home.mp3",
    play: true,
  },
  {
    name: "I Feel Love",
    artist: "Donna Summer",
    objectKey: "jMusic/i Feel Love, DS.mp3",
    play: true,
  },
  {
    name: "Unwritten",
    artist: "Natasha Bedingfield",
    objectKey: "jMusic/Unwritten.mp3",
    play: true,
  },
  {
    name: "You Make Me Happy",
    artist: "My Sun & Stars",
    objectKey: "jMusic/You make me happy.mp3",
    play: true,
  },
  {
    name: "One Night in Bangkok",
    artist: "Murray Head",
    objectKey: "jMusic/One Night In Bangkok.mp3",
    play: true,
  },
  {
    name: "You are the Best Thing",
    artist: "Ray LaMontagne",
    objectKey: "jMusic/You're My Best Friend.mp3",
    play: true,
  },
  {
    name: "Don't Stop Believin'",
    artist: "Journey",
    objectKey: "jMusic/Don't Stop Believin'.mp3",
    play: true,
  },
  {
    name: "Mamma Mia",
    artist: "ABBA",
    objectKey: "jMusic/Mamma Mia.mp3",
    play: true,
  },
  {
    name: "I wanna know what love is",
    artist: "Foreigner",
    objectKey: "jMusic/I Want to Know What Love Is.mp3",
    play: true,
  },
  {
    name: "Goodbye Yellow Brick Road",
    artist: "Elton John",
    objectKey: "jMusic/Goodbye Yellow Brick Road.mp3",
    play: true,
  },
  {
    name: "Nikita",
    artist: "Elton John",
    objectKey: "jMusic/Nikita.mp3",
    play: true,
  },
  {
    name: "I'm Still Standing",
    artist: "Elton John",
    objectKey: "jMusic/I'm Still Standing.mp3",
    play: true,
  },
  {
    name: "Dont Stop Me Now",
    artist: "Queen",
    objectKey: "jMusic/Don't Stop Me Now.mp3",
    play: true,
  },
  {
    name: "Don't Go Breaking My Heart",
    artist: "Elton John & Kiki Dee",
    objectKey: "jMusic/Don't Go Breaking My Heart (Remas.mp3",
    play: true,
  },
  {
    name: "Shallow",
    artist: "Lady Gaga & Bradley Cooper",
    objectKey: "jMusic/Shallow.mp3",
    play: true,
  },
  {
    name: "Music To My Eyes",
    artist: "Lady Gaga & Bradley Cooper",
    objectKey: "jMusic/Music To My Eyes.mp3",
    play: true,
  },
  {
    name: "Always Remember Us This Way",
    artist: "Lady Gaga and Bradley Cooper",
    objectKey: "jMusic/Always Remember Us This Way.mp3",
    play: true,
  },
  {
    name: "We Are the Champions",
    artist: "Queen",
    objectKey: "jMusic/We Are the Champions.mp3",
    play: true,
  },
  {
    name: "Hotel California",
    artist: "Eagles",
    objectKey: "jMusic/Hotel California.mp3",
    play: true,
  },
  {
    name: "Rocketman",
    artist: "Elton John",
    objectKey: "jMusic/Rocket Man (I Think It's Going to.mp3",
    play: true,
  },
  {
    name: "Somewhere Over the Rainbow",
    artist: "Israel Kamakawiwoole",
    objectKey: "jMusic/Over the Rainbow BrotherIs.mp3",
    play: true,
  },
  {
    name: "Free to wear sunscreen",
    artist: "Baz Luhrman",
    objectKey: "jMusic/Everybody's Free (To Wear Sunscreen) [Edit].mp3",
    play: true,
  },
  {
    name: "Wonderful",
    artist: "Tones & I",
    objectKey: "jMusic/Wonderful.mp3",
    play: true,
  },
  {
    name: "I Will Survive",
    artist: "Cake",
    objectKey: "jMusic/I Will Survive.mp3",
    play: true,
  },
  {
    name: "Never Enough",
    artist: "Loren Allred",
    objectKey: "jMusic/Never Enough.mp3",
    play: true,
  },
  {
    name: "Sail Away",
    artist: "David Gray",
    objectKey: "jMusic/Sail Away.mp3",
    play: true,
  },
  {
    name: "Takes a lot to know a Man",
    artist: "Damien Rice",
    objectKey: "jMusic/It Takes a Lot to Know a Man.mp3",
    play: true,
  },
  {
    name: "Better Together",
    artist: "Jack Johnson",
    objectKey: "jMusic/Better Together.mp3",
    play: true,
  },
  {
    name: "Love you Madly",
    artist: "Cake",
    objectKey: "jMusic/Love You Madly.mp3",
    play: true,
  },
  {
    name: "Short Skirt, Long Jacket",
    artist: "Cake",
    objectKey: "jMusic/Short Skirt_Long Jacket.mp3",
    play: true,
  },
  {
    name: "Cat People - Putting Out Fire",
    artist: "David Bowie",
    objectKey: "jMusic/Cat People (Putting Out Fire).mp3",
    play: true,
  },
  {
    name: "Perhaps, Perhaps, Perhaps",
    artist: "Cake",
    objectKey: "jMusic/Perhaps, Perhaps, Perhaps.mp3",
    play: true,
  },
  {
    name: "Everyody's Gotta Learn Sometime",
    artist: "The Korgis",
    objectKey: "https://dl.dropboxusercontent.com/scl/fi/9yeu212ucgfwox8t7q4rs/01-Everybody-s-Got-To-Learn-Sometime.mp3?rlkey=uyvuepch4r6gg2evws8xtsvaq&st=fanctea2&dl=0",
    play: true,
  },
  {
    name: "Roads",
    artist: "Portishead",
    objectKey: "jMusic/Roads.mp3",
    play: true,
  },
  {
    name: "Sour Times",
    artist: "Portishead",
    objectKey: "jMusic/Sour Times.mp3",
    play: true,
  },
  {
    name: "Hot Gates",
    artist: "Mumford & Sons",
    objectKey: "jMusic/Hot Gates.mp3",
    play: true,
  },

  {
    name: "Adventure of a Lifetime",
    artist: "Coldplay",
    objectKey: "jMusic/Adventure Of A Lifetime.mp3",
    play: true,
  },
  {
    name: "Afterlife",
    artist: "Ingrid Michaelson",
    objectKey: "jMusic/Afterlife.mp3",
    play: true,
  },
  {
    name: "Night We Met",
    artist: "Lord Huron",
    objectKey: "jMusic/The Night We Met.mp3",
    play: true,
  },
  {
    name: "Love is like Ghosts",
    artist: "Lord Huron",
    objectKey: "jMusic/Love Like Ghosts.mp3",
    play: true,
  },
  {
    name: "Soldier",
    artist: "Ingrid Michaelson",
    objectKey: "jMusic/Soldier.mp3",
    play: true,
  },
  {
    name: "Everybody",
    artist: "Ingrid Michaelson",
    objectKey: "jMusic/Everybody.mp3",
    play: true,
  },
  {
    name: "Automatic",
    artist: "The Lumineers",
    objectKey: "jMusic/Automatic.mp3",
    play: true,
  },
  {
    name: "Hey",
    artist: "The Lumineers",
    objectKey: "jMusic/Ho Hey.mp3",
    play: true,
  },
  {
    name: "Woman",
    artist: "Mumford & Sons",
    objectKey: "jMusic/Woman.mp3",
    play: true,
  },
  {
    name: "We saw gold",
    artist: "Tones & I",
    objectKey: "jMusic/I Get High.mp3",
    play: true,
  },
  {
    name: "PNAU Mix",
    artist: "Elton John",
    objectKey: "jMusic/Cold Heart (PNAU Remix).mp3",
    play: true,
  },
  {
    name: "Bad Child",
    artist: "Tones & I",
    objectKey: "jMusic/Bad Child.mp3",
    play: true,
  },
  {
    name: "Death Wish Love",
    artist: "Boone",
    objectKey: "jMusic/Death Wish Love.mp3",
    play: true,
  },
  {
    name: "I Am The Highway",
    artist: "Audioslave",
    objectKey: "jMusic/I Am The Highway.mp3",
    play: true,
  },
  {
    name: "Pretty Slowly",
    artist: "Boone",
    objectKey: "jMusic/Pretty Slowly.mp3",
    play: true,
  },
  {
    name: "Relax My Beloved",
    artist: "Alex Clare",
    objectKey: "jMusic/Relax My Beloved.mp3",
    play: true,
  },
  {
    name: "Too Close",
    artist: "Alex Clare",
    objectKey: "jMusic/Too Close.mp3",
    play: true,
  },
  {
    name: "Wilder Mind",
    artist: "Mumford & Sons",
    objectKey: "jMusic/Wilder Mind.mp3",
    play: true,
  },
  {
    name: "You and Me",
    artist: "Yelawolf",
    objectKey: "jMusic/You and Me.mp3",
    play: true,
  },
  {
    name: "Angel By The Wings",
    artist: "Sia",
    objectKey: "jMusic/Angel By The Wings.mp3",
    play: true,
  },
  {
    name: "Anybody Listening",
    artist: "Scorpions",
    objectKey: "jMusic/Anybody Listening_.mp3",
    play: true,
  },
  {
    name: "Beautiful Things",
    artist: "Boone",
    objectKey: "jMusic/Beautiful Things.mp3",
    play: true,
  },
  {
    name: "The Craving",
    artist: "Boone",
    objectKey: "jMusic/The Craving (Jenna's version).mp3",
    play: true,
  },
  {
    name: "Volcano",
    artist: "Damien Rice",
    objectKey: "jMusic/Volcano.mp3",
    play: true,
  },
  {
    name: "Good Girls Go to Hell",
    artist: "Billie Eilish",
    objectKey: "jMusic/all the good girls go to hell.mp3",
    play: true,
  },
  {
    name: "Jive Talkin",
    artist: "BeeGees",
    objectKey: "jMusic/Jive Talkin'.mp3",
    play: true,
  },
  {
    name: "Bohemian Rhapsody",
    artist: "Queen",
    objectKey: "jMusic/Bohemian Rhapsody.mp3",
    play: true,
  },
  {
    name: "Another One Bites the Dust",
    artist: "Queen",
    objectKey: "jMusic/Another One Bites the Dust.mp3",
    play: true,
  },
  {
    name: "Under Pressure",
    artist: "Queen",
    objectKey: "jMusic/Under Pressure (Remastered 21 _.mp3",
    play: true,
  },
  {
    name: "Crazy Little Thing Called Love",
    artist: "Queen",
    objectKey: "jMusic/Crazy Little Thing Called Love (2.mp3",
    play: true,
  },
  {
    name: "Songbird",
    artist: "Fleetwood Mac",
    objectKey: "jMusic/Songbird.mp3",
    play: true,
  },
  {
    name: "Nevermore",
    artist: "Queen",
    objectKey: "jMusic/Nevermore.mp3",
    play: true,
  },
  {
    name: "Love So Right",
    artist: "BeeGees",
    objectKey: "jMusic/Love So Right.mp3",
    play: true,
  },
  {
    name: "You're My Best Friend",
    artist: "Queen",
    objectKey: "jMusic/You're My Best Friend.mp3",
    play: true,
  },
  {
    name: "How Deep Is Your Love",
    artist: "BeeGees",
    objectKey: "jMusic/How Deep Is Your Love.mp3",
    play: true,
  },
  {
    name: "Grenade",
    artist: "Bruno Mars",
    objectKey: "jMusic/Grenade.mp3",
    play: true,
  },
  {
    name: "Back to Black",
    artist: "Amy Winehouse",
    objectKey: "jMusic/Back To Black.mp3",
    play: true,
  },
  {
    name: "Don't Fear the Reaper",
    artist: "Blue Oyster Cult",
    objectKey: "jMusic/(Don't Fear) The Reaper.mp3",
    play: true,
  },
  {
    name: "You Should Be Dancing",
    artist: "BeeGees",
    objectKey: "jMusic/You Should Be Dancing.mp3",
    play: true,
  },
  {
    name: "More Than a Woman",
    artist: "BeeGees",
    objectKey: "jMusic/More Than A Woman.mp3",
    play: true,
  },
  {
    name: "Tragedy",
    artist: "BeeGees",
    objectKey: "jMusic/Tragedy.mp3",
    play: true,
  },
  {
    name: "My Life",
    artist: "Billy Joel",
    objectKey: "jMusic/My life.mp3",
    play: true,
  },
  {
    name: "You Stepped Into My Life",
    artist: "BeeGees",
    objectKey: "jMusic/You Stepped Into My Life.mp3",
    play: true,
  },
  {
    name: "Tell Me You Love Me",
    artist: "Demi Lovato",
    objectKey: "jMusic/Tell Me You Love Me.mp3",
    play: true,
  },
  {
    name: "Piano Man",
    artist: "Billy Joel",
    objectKey: "jMusic/Piano Man.mp3",
    play: true,
  },
  {
    name: "Night Fever",
    artist: "BeeGees",
    objectKey: "jMusic/Night Fever.mp3",
    play: true,
  },
  {
    name: "Big Mistake",
    artist: "Natalie Imbruglia",
    objectKey: "jMusic/Big Mistake.mp3",
    play: true,
  },
  {
    name: "Superman",
    artist: "Sterophonics",
    objectKey: "jMusic/Superman.mp3",
    play: true,
  },
  {
    name: "Green Eyes",
    artist: "Coldplay",
    objectKey: "jMusic/Green Eyes.mp3",
    play: true,
  },
  {
    name: "Forgiven",
    artist: "Alanis Morissette",
    objectKey: "jMusic/Forgiven.mp3",
    play: true,
  },
]