//updated 04/21/2026
// Primary built-in library for the impala instance.
const songsKw = [
  {
    name: "You're My Everything",
    artist: "Anita Baker",
    objectKey: "Anita Baker/[2004] Baker, Anita - My Everything/Baker, Anita - My Everything - 01 - You're My Everything.flac",
    play: true,
  },
  {
    name: "How Could You",
    artist: "Anita Baker",
    objectKey: "Anita Baker/[2004] Baker, Anita - My Everything/Baker, Anita - My Everything - 02 - How Could You.flac",
    play: true,
  },
  {
    name: "Another One Bites The Dust",
    artist: "Queen",
    objectKey: "OriginalMusic/01 Another One Bites The Dust (2011.mp3",
    play: true,
  },
  {
    name: "Bohemian Rhapsody",
    artist: "Queen",
    objectKey: "OriginalMusic/01 Bohemian Rhapsody.mp3",
    play: true,
  },
  {

    name: "Everybody's Free (To Wear Sunscreen)",
    artist: "Baz Luhrmann",
    objectKey: "OriginalMusic/01 Everybody's Free (To Wear Sunscreen) [Edit].mp3",
    play: true,
  },
  {
    name: "Everybody's Got To Learn Sometime",
    artist: "The Korgis",
    objectKey: "OriginalMusic/01 Everybody's Got To Learn Sometime.mp3",
    play: true,
  },
  {
    name: "Flowers",
    artist: "Miley Cyrus",
    objectKey: "OriginalMusic/01 Flowers.mp3",
    play: true,
  },
  {
    name: "Glycerine",
    artist: "Goo Goo Dolls",
    objectKey: "OriginalMusic/01 Glycerine.mp3",
    play: true,
  },
  {
    name: "Hotel California",
    artist: "Eagles",
    objectKey: "OriginalMusic/01 Hotel California.mp3",
    play: true,
  },
  {
    name: "I'm Only Joking",
    artist: "Dave Matthews Band",
    objectKey: "OriginalMusic/01 I'm Only Joking.mp3",
    play: true,
  },
  {
    name: "Jive Talkin'",
    artist: "Bee Gees",
    objectKey: "OriginalMusic/01 Jive Talkin'.mp3",
    play: true,
  },
  {
    name: "Love Like Ghosts",
    artist: "Lord Huron",
    objectKey: "OriginalMusic/01 Love Like Ghosts.mp3",
    play: true,
  },
  {
    name: "Mamma Mia",
    artist: "ABBA",
    objectKey: "OriginalMusic/01 Mamma Mia.mp3",
    play: true,
  },
  {
    name: "Rocket Man",
    artist: "Elton John",
    objectKey: "OriginalMusic/01 Rocket Man (I Think It's Going to.mp3",
    play: true,
  },
  {
    name: "Soldier",
    artist: "Ingrid Michaelson",
    objectKey: "OriginalMusic/01 Soldier.mp3",
    play: true,
  },
  {
    name: "Sorry Not Sorry",
    artist: "Demi Lovato",
    objectKey: "OriginalMusic/01 Sorry Not Sorry.mp3",
    play: true,
  },
  {
    name: "Twist in My Sobriety",
    artist: "Tanita Tikaram",
    objectKey: "OriginalMusic/01 Twist In My Sobriety.mp3",
    play: true,
  },
  {
    name: "Another One Bites the Dust",
    artist: "Queen",
    objectKey: "OriginalMusic/02 Another One Bites the Dust.mp3",
    play: true,
  },
  {
    name: "Come with me now",
    artist: "Kongos",
    objectKey: "OriginalMusic/02 Come With Me Now.mp3",
    play: true,
  },
  {
    name: "Everybody",
    artist: "Ingrid Michaelson",
    objectKey: "OriginalMusic/02 Everybody.mp3",
    play: true,
  },
  {
    name: "It Takes a Lot to Know a Man",
    artist: "Damien Rice",
    objectKey: "OriginalMusic/02 It Takes a Lot to Know a Man.mp3",
    play: true,
  },
  {
    name: "Night Fever",
    artist: "Bee Gees",
    objectKey: "OriginalMusic/02 Night Fever.mp3",
    play: true,
  },
  {
    name: "Piano Man",
    artist: "Billy Joel",
    objectKey: "OriginalMusic/02 Piano Man.mp3",
    play: true,
  },
  {
    name: "Tell Me You Love Me",
    artist: "Demi Lovato",
    objectKey: "OriginalMusic/02 Tell Me You Love Me.mp3",
    play: true,
  },
  {
    name: "You Stepped Into My Life",
    artist: "Melba Moore",
    objectKey: "OriginalMusic/02 You Stepped Into My Life.mp3",
    play: true,
  },
  {
    name: "Beloved Wife",
    artist: "Natalie Merchant",
    objectKey: "OriginalMusic/03 - Natalie Merchant - Beloved Wife.mp3",
    play: true,
  },
  {
    name: "Killer Queen",
    artist: "Queen",
    objectKey: "OriginalMusic/03 Killer Queen.mp3",
    play: true,
  },
  {
    name: "My Life",
    artist: "Billy Joel",
    objectKey: "OriginalMusic/03 My life.mp3",
    play: true,
  },
  {
    name: "Tragedy",
    artist: "Bee Gees",
    objectKey: "OriginalMusic/03 Tragedy.mp3",
    play: true,
  },
  {
    name: "Shilo",
    artist: "Neil Diamond",
    objectKey: "OriginalMusic/03. Shilo.mp3",
    play: true,
  },
  {
    name: "Someone You Loved",
    artist: "Lewis Capaldi",
    objectKey: "OriginalMusic/03. Someone You Loved.mp3",
    play: true,
  },
  {
    name: "GGoodbye Yellow Brick Road",
    artist: "Elton John",
    objectKey: "OriginalMusic/04 Goodbye Yellow Brick Road.mp3",
    play: true,
  },
  {
    name: "More than a Woman",
    artist: "Bee Gees",
    objectKey: "OriginalMusic/04 More Than A Woman.mp3",
    play: true,
  },
  {
    name: "Short Skirt, Long Jacket",
    artist: "Cake",
    objectKey: "OriginalMusic/04 Short Skirt_Long Jacket.mp3",
    play: true,
  },
  {
    name: "You Should Be Dancing",
    artist: "Bee Gees",
    objectKey: "OriginalMusic/04 You Should Be Dancing.mp3",
    play: true,
  },
  {
    name: "Automatic",
    artist: "The Lumineers",
    objectKey: "OriginalMusic/04. Automatic.mp3",
    play: true,
  },
  {
    name: "(Don't Fear) The Reaper",
    artist: "Blue Öyster Cult",
    objectKey: "OriginalMusic/05 (Don't Fear) The Reaper.mp3",
    play: true,
  },
  {
    name: "Black",
    artist: "Pearl Jam",
    objectKey: "OriginalMusic/05 -Black.flac",
    play: true,
  },
  {
    name: "Adventure Of A Lifetime",
    artist: "Coldplay",
    objectKey: "OriginalMusic/05 Adventure Of A Lifetime.mp3",
    play: true,
  },
  {
    name: "Back To Black",
    artist: "Amy Winehouse",
    objectKey: "OriginalMusic/05 Back To Black.mp3",
    play: true,
  },
  {
    name: "Commissioning a Symphony in C",
    artist: "Cake",
    objectKey: "OriginalMusic/05 Commissioning a Symphony in C.mp3",
    play: true,
  },
  {
    name: "Dont stop believin'",
    artist: "Journey",
    objectKey: "OriginalMusic/05 Don't Stop Believin'.mp3",
    play: true,
  },
  {
    name: "Grenade",
    artist: "Bruno Mars",
    objectKey: "OriginalMusic/05 Grenade.mp3",
    play: true,
  },
  {
    name: "Ho Hey",
    artist: "The Lumineers",
    objectKey: "OriginalMusic/05 Ho Hey.mp3",
    play: true,
  },
  {
    name: "Incredible Love",
    artist: "Demi Lovato",
    objectKey: "OriginalMusic/05 Incredible Love.mp3",
    play: true,
  },
  {
    name: "Nikita",
    artist: "Elton John",
    objectKey: "OriginalMusic/05 Nikita.mp3",
    play: true,
  },
  {
    name: "Something I Can Never Have",
    artist: "Nine Inch Nails",
    objectKey: "OriginalMusic/05. Something I Can Never Have.mp3",
    play: true,
  },
  {
    name: "How Deep Is Your Love",
    artist: "Bee Gees",
    objectKey: "OriginalMusic/06 How Deep Is Your Love.mp3",
    play: true,
  },
  {
    name: "Im Still Standing",
    artist: "Elton John",
    objectKey: "OriginalMusic/06 I'm Still Standing.mp3",
    play: true,
  },
  {
    name: "You're My Best Friend",
    artist: "Queen",
    objectKey: "OriginalMusic/06 You're My Best Friend.mp3",
    play: true,
  },
  {
    name: "Dont Stop Me Now",
    artist: "Queen",
    objectKey: "OriginalMusic/07 Don't Stop Me Now.mp3",
    play: true,
  },
  {
    name: "Green Eyes",
    artist: "Coldplay",
    objectKey: "OriginalMusic/07 Green Eyes.mp3",
    play: true,
  },
  {
    name: "I Will Survive",
    artist: "Gloria Gaynor",
    objectKey: "OriginalMusic/07 I Will Survive.mp3",
    play: true,
  },
  {
    name: "Love So Right",
    artist: "Bee Gees",
    objectKey: "OriginalMusic/07 Love So Right.mp3",
    play: true,
  },
  {
    name: "Wonderful",
    artist: "Everclear",
    objectKey: "OriginalMusic/07. Wonderful.mp3",
    play: true,
  },
  {
    name: "Don't Go Breaking My Heart",
    artist: "Elton John & Kiki Dee",
    objectKey: "OriginalMusic/08 Don't Go Breaking My Heart (Remas.mp3",
    play: true,
  },
  {
    name: "Nevermore",
    artist: "Queen",
    objectKey: "OriginalMusic/08 Nevermore.mp3",
    play: true,
  },
  {
    name: "Love you Madly",
    artist: "Cake",
    objectKey: "OriginalMusic/09 Love You Madly.mp3",
    play: true,
  },
  {
    name: "Perhaps, Perhaps, Perhaps",
    artist: "Cake",
    objectKey: "OriginalMusic/09 Perhaps, Perhaps, Perhaps.mp3",
    play: true,
  },
  {
    name: "Sail Away",
    artist: "David Gray",
    objectKey: "OriginalMusic/09 Sail Away.mp3",
    play: true,
  },
  {
    name: "Bored",
    artist: "Billie Eilish",
    objectKey: "OriginalMusic/1-01 Bored.mp3",
    play: true,
  },
  {
    name: "Mandy",
    artist: "Barry Manilow",
    objectKey: "OriginalMusic/1-01 Mandy.mp3",
    play: true,
  },
  {
    name: "Shape of You",
    artist: "Ed Sheeran",
    objectKey: "OriginalMusic/1-01 Shape of You (feat. Nyla & Kran.mp3",
    play: true,
  },
  {
    name: "Bad Guy",
    artist: "Billie Eilish",
    objectKey: "OriginalMusic/1-02 bad guy.mp3",
    play: true,
  },
  {
    name: "Girls Just Want To Have Fun",
    artist: "Cyndi Lauper",
    objectKey: "OriginalMusic/1-02 Girls Just Want To Have Fun.mp3",
    play: true,
  },
  {
    name: "Sour Times",
    artist: "Portishead",
    objectKey: "OriginalMusic/1-02 Sour Times.mp3",
    play: true,
  },
  {
    name: "Big Mistake",
    artist: "Natalie Imbruglia",
    objectKey: "OriginalMusic/1-03 Big Mistake.mp3",
    play: true,
  },
  {
    name: "Woman",
    artist: "Mumford & Sons",
    objectKey: "OriginalMusic/1-03 Woman.mp3",
    play: true,
  },
  {
    name: "Beloved",
    artist: "Mumford & Sons",
    objectKey: "OriginalMusic/1-04 Beloved.mp3",
    play: true,
  },
  {
    name: "Time After Time",
    artist: "Cyndi Lauper",
    objectKey: "OriginalMusic/1-04 Time After Time.mp3",
    play: true,
  },
  {
    name: "True Colors",
    artist: "Cyndi Lauper",
    objectKey: "OriginalMusic/1-04 True Colors.mp3",
    play: true,
  },
  {
    name: "All the Good Girls Go to Hell",
    artist: "Billie Eilish",
    objectKey: "OriginalMusic/1-05 all the good girls go to hell.mp3",
    play: true,
  },
  {
    name: "Never Enough",
    artist: "Loren Allred",
    objectKey: "OriginalMusic/1-06 Never Enough.mp3",
    play: true,
  },
  {
    name: "Photograph",
    artist: "Ed Sheeran",
    objectKey: "OriginalMusic/1-06 Photograph.mp3",
    play: true,
  },
  {
    name: "Roads",
    artist: "Portishead",
    objectKey: "OriginalMusic/1-08 Roads.mp3",
    play: true,
  },
  {
    name: "Hot Gates",
    artist: "Mumford & Sons",
    objectKey: "OriginalMusic/1-12 Hot Gates.mp3",
    play: true,
  },
  {
    name: "Holly Holy",
    artist: "Neil Diamond",
    objectKey: "OriginalMusic/1-13 Holly Holy.mp3",
    play: true,
  },
  {
    name: "Behind Blue Eyes",
    artist: "Limp Bizkit",
    objectKey: "OriginalMusic/1-15 Behind Blue Eyes.mp3",
    play: true,
  },
  {
    name: "Soolaimón",
    artist: "Neil Diamond",
    objectKey: "OriginalMusic/1-20 Soolaimón.mp3",
    play: true,
  },
  {
    name: "I Want to Know What Love Is",
    artist: "Foreigner",
    objectKey: "OriginalMusic/1-286 I Want to Know What Love Is (1.mp3",
    play: true,
  },
  {
    name: "AA",
    artist: "Walker Hayes",
    objectKey: "OriginalMusic/1-61 AA.mp3",
    play: true,
  },
  {
    name: "Cat People (Putting Out Fire)",
    artist: "David Bowie",
    objectKey: "OriginalMusic/1-663 Cat People (Putting Out Fire).mp3",
    play: true,
  },
  {
    name: "Sail",
    artist: "AWOLNATION",
    objectKey: "OriginalMusic/10 Sail.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/10. Ignite.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/11 Outside.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/11 Thinking Out Loud.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/12 Afterlife.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/12 Shallow.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/12 Songbird.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/13. Legends Never Die.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/14 Can't Stop Lovin' You.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/14 Music To My Eyes.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/14 The Night We Met.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/17 Always Remember Us This Way.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/17 We Are the Champions.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/2-01 I Am... I Said.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/2-01 Superman.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/2-03 Arsonist's Lullabye.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/2-07 I Think It's Gonna Rain Today.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/2-12 Play Me.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/21 Under Pressure (Remastered 2011 _.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/58 Crazy Little Thing Called Love (2.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/A Flock of Seagulls  I Ran So Far Away.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/All My Love (Remaster).mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/All the Debts I Owe.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Angel By The Wings.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Anybody Listening_.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Bad Child.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Bailey Zimmerman - Rock and A Hard Place (Official Music Video).mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Beautiful Things.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Bob Seger - Turn The Page (1973 Radio Version).mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Chris Stapleton - Tennessee Whiskey (Official Audio).mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Cody Johnson - Travelin' Soldier (Acoustic).mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Cold Heart (PNAU Remix).mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Coming Undone.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Corey Hart  Sunglasses at Night  (HQ).mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Death Wish Love.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Donna Summer - I Feel Love (Official Music Video).mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Donna Summer - Last Dance (HQ).mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Eminem - Somebody Save Me (feat. Jelly Roll) [Official Music Video].mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Eminem ft Jelly Roll & Rihanna - Tomorrow For Us (2026 Music Video).mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Empty Chair.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Fireflight - Unbreakable.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Fireflight - You Decide.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Flyleaf - All Around Me (Official Music Video).mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Forgiven.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Frankie Valli - Can't Take My Eyes Off You (Lyrics).mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Happy.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Have It All - Jason Mraz (Lyrics).mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Heartbreaking After Im Gone By MICHAEL BENNET Americas Got Talent 8 min !!! -...",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Home.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Hozier - Too Sweet (Official Lyric Video).mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Hozier No Plan.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/I Am The Highway.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/i Feel Love, DS.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/I Get High.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/I Spy.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Is There A Ghost.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Jackson Dean - Wings (Lyric Video).mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/James Bay - Let It Go.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Jelly Roll - Son Of A Sinner (Official Music Video).mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Led Zeppelin - Thank You.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/LEDGER_ Not Dead Yet [OFFICIAL VIDEO].mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Leonard Cohen - You Want It Darker (Official Audio).mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/LISA O'NEILL Blackbird.mp4",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Long Time Traveller-wailingJennys.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Love On The Rocks.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Love, Reign O'er Me- Pearl Jam.mp3",
    play: true,
  },
  {
    name: "name",
    artist: "artist",
    objectKey: "OriginalMusic/Mama's Broken Heart.mp3",
    play: true,
  },
  {
    name: "The Silence",
    artist: "Manchester Orchestra",
    objectKey: "OriginalMusic/Manchester Orchestra - The Silence (Official Music Video).mp3",
    play: true,
  },

];
